# docker-compose.preview.yml  (repo-root에 위치)
services:
  fe-preview:
    image: fe-preview:${IMAGE_TAG}
    build:
      # 👉  빌드 컨텍스트를 런타임 변수로 치환
      context: ./FE/${FE_APP}
      dockerfile: Dockerfile.preview
      args:
        BASE_PATH: ${BASE_PATH}
    environment: {}
      # FE가 dev BE를 바라보도록 - 현재는 주석
      #VITE_API_URL: http://{SPRING_CONTAINER_NAME}


networks:
  app-network:
    external: true