version: '3.8'

services:
  chroma:
    image: chromadb/chroma:0.4.24
    ports: ["8001:8000"]
    volumes:
      - chroma-data:/chroma/.chroma

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8000:8000"]
    volumes:
      - ./app:/app/app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DB=${MYSQL_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - CHROMA_HOST=${CHROMA_HOST}
      - COLLECTION_NAME=${COLLECTION_NAME}
    depends_on:
      chroma:
        condition: service_started 
      redis:
        condition: service_started

volumes:
  chroma-data:
  redis-data: