version: '3.8'

services:
  api:
    build: .
    container_name: voice-kiosk-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DB=${MYSQL_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}