spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: never  # 모든 데이터베이스로 초기화 대상 변경
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
  
jwt:
  secret: ${JWT_SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: mylio-bucket

logging.level:
  org.hibernate.SQL: info

app:
  domain:
    url: https://k12b102.p.ssafy.io
    cors-origins: https://k12b102.p.ssafy.io,http://localhost:5173
  is-local: false
  cookie-domain: k12b102.p.ssafy.io