server:
  servlet:
    context-path: /api

spring:
  application:
    name: mylio
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  profiles:
    include: secret
    active: dev

  # jackson:
  #   property-naming-strategy: SNAKE_CASE

  data:
    web:
      pageable:
        one-indexed-parameters: true  # 페이징 1부터


management:
  endpoints:
    web:
      base-path: /api/actuator