spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: never  # 모든 데이터베이스로 초기화 대상 변경
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis-dev

logging.level:
  org.hibernate.SQL: info

app:
  domain:
    url: https://k12b102.p.ssafy.io
    cors-origins: https://k12b102.p.ssafy.io, http://localhost:5173
  is-local: false
  cookie-domain: k12b102.p.ssafy.io